import re
import sys
import tomllib
from cx_Freeze import setup, Executable
from cx_Freeze.command.bdist_appimage import bdist_appimage as _bdist_appimage


class bdist_appimage(_bdist_appimage):
    """Patch the .desktop entry generated by cx_Freeze.

    cx_Freeze emits an invalid icon reference (`Icon=/share/icons/icon`),
    which is an absolute path that exists neither on the host nor inside
    the AppImage in a resolvable form. Rewrite it to the app icon name
    (the icon is exported at $APPDIR/<name>.png and $APPDIR/share/icons/),
    per the Desktop Entry spec, so tools harvesting the entry (appctl,
    AppImageLauncher, desktop environments) can resolve it.
    """

    def save_as_file(self, data, outfile, mode="r"):
        if isinstance(data, str) and outfile.endswith(".desktop"):
            # e.g. Icon=/share/icons/icon -> Icon=koradgui
            data = re.sub(r"(?m)^Icon=/.*$", f"Icon={self.target_name}", data)
        return super().save_as_file(data, outfile, mode)

with open("pyproject.toml", "rb") as f:
    _version = tomllib.load(f)["project"]["version"]

# Dependencies are automatically detected, but they might need fine-tuning.
build_exe_options = {
     "include_files": ["assets/"],
     "excludes": ["tkinter", "unittest"],
     "optimize": 2,
     "zip_include_packages": ["*"],
     "zip_exclude_packages": ["imgui_bundle", "numpy", "koradgui"],
}

_icon = "assets/app_settings/icon.png"
if sys.platform == "win32":
    # Windows needs .ico; bundle the VC++ runtime DLLs so the zip is self-contained
    _icon = "assets/app_settings/icon.ico"
    build_exe_options["include_msvcr"] = True

setup(
    name="koradGui",
    version=_version,
    description="koradGui",
    options={"build_exe": build_exe_options},
    cmdclass={"bdist_appimage": bdist_appimage},
    executables=[Executable("koradgui/main.py", base="gui", target_name="koradGui",
                            icon=_icon)],
)